src-plugins/itkFilters/itkFiltersThresholdingProcess_p.h
:cactus: 
Plop
"output->copyMetaDataFrom(input);" was missing in itkFiltersThresholdingProcess in order to save metadata from input to output.
Mathilde M.
:hamster:
=> debug copymetadata missing in itkFiltersThresholdingProcess

src-plugins/medSegmentation/msegAlgorithmPaintToolbox.cpp, src-plugins/medSegmentation/msegAlgorithmPaintToolbox.h
In your current version of Paint Segmentation, every time you click on the volume (for painting) the algo goes through every layer of the view and checks whether the layer has already been painted. If not, it sets the data.
This loop is really slowing down the painting; after each click, there is half-second "freeze" during which the motion of the mouse is not taken into account; which makes the use of the tool quite disturbing/annoying.
What I did was removing this loop and setting the data in the clearMask method, because I think the only times you need to set the data is when you change the data (managed by updateView) or when you reset your mask after saving it (meaning that you want to start a new segmentation, thus create a new mask).
I decided to get rid of the multi-layer …
=> [PaintTbx] Improving usability, getting rid of multi-layer  management and removing useless code

src/medCore/parameters/medCompositeParameter.cpp, src/medCore/parameters/medCompositeParameter.h
With the current *values()* method, the QList returned comes from *QHash::values()*; its order is arbitrary.
We had this problem in MUSIC (https://github.com/Inria-Asclepios/music/pull/30) where we wanted to get the windowing parameters through the *windowLevelParameter* but we were not able to be sure whether the level would come first (in the QList) or the window width ...
So I created a new *medCompositeParameter::values(QString)* method which takes the key of the hash as argument.
Now, to have the window level we just use *compositeParameter->values("Level")[0]*
=> Adds new method values(QString) to medCompositeParameter

src/medVtkInria/vtkDataManagement/vtkMetaDataSet.cxx
Similar commit has been approved by medInria guys: https://github.com/medInria/medInria-public/pull/234
Pb was we couldn't find *isNan()* method that works both for Mac and Windows (and VS 2010-12)
=> A solution to the isNan pb on Mac and Windows

src-plugins/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Needed if we want to automatically set intensity range when displaying a mesh (only the linkable parameters are, for now, accessible)
Either we set min/MaxRange as linkable parameters, or we create a new method that returns all the parameters of an interactor.
=> Adds Min/Max range as linkable parameters for meshes

src/medVtkInria/vtkWidgetsAddOn/vtkInteractorStyleTrackballCamera2.cxx
When rotating the camera round the x-axis, we correctly set the camera y-axis. Unfortunately, when rotating around the z-axis, this code is handled by vtk directly rather than our own code.
This means that the camera's actual y-axis was not being stored, which meant that rotating around the y-axis (when rotating in the horizontal plane) was not working correctly, as we were using outdated y-axis information.
The new code now gets the y-axis 'live', rather than relying on a stored variable.
=> Fix broken camera rotation

src/medCore/views/medAbstractView.h
In the plugins we can use `navigators()` instead of `extraNavigators()`, so let's keep this one protected as in medInria-public.
=> extraNavigators back to protected

src/medCore/process/medAbstractProcess.h
When calling the previous setInput() on a process coming from the dtkAbstractProcessFactory, we are going inside the `dtkAbstractProcess::setInput()` and not inside the setInput() of our process.
(To be sure of that try the scarAnalysisTbx)
That's why we need our own method.
=> new setInput method, virtual with default second parameter

src-plugins/itkDataImage/datas/itkDataPrivateTypes.h
With current code, no histogram is displayed if the image contains negative values.
=> [HISTOG] Corrects bug with images with negative values

src-plugins/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp, src-plugins/vtkDataMesh/interactors/vtkDataMeshInteractor.h
When saving the scene, we save all the rendering parameters, but forget to use the windowing ones when opening the scene.
=> When loading a scene, set the right windowing

src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medAbstractDatabaseImporter.h, src/medCore/database/medDatabaseNonPersistentImporter.cpp
When saving non-persistently a **data**, it was actually writing the file on the db.
When saving non-persistently a **file**, it works fine.
This difference in behavior is due to two ```medAbstractDatabaseImporter``` constructors, one taking care of setting the boolean ```indexWithoutImporting```, the other setting it to false.
And it's this boolean that tells whether you want to write the data on the disk or not.
To see if this PR works, just check the size (and number of files in your db) before and after any operation that creates a non-persistent data. These numbers shouldn't change.
=> Prevents from writing on the disk when saving DATA non-persistently

src-plugins/itkFilters/itkFiltersToolBox.cpp
Probably corrects the crash Mathilde reported a previous email.
Small part of the crash log:
*terminating with uncaught exception of type itk::ExceptionObject: /Users/buildbot/dev/MUSIC/medinria-superproject/ITK/Modules/Core/Common/include/itkImageBase.hxx:191:
itk::ERROR: Image(0x1287be6d0): A spacing of 0 is not allowed: Spacing is [3.69141, 2.21484, 0]*
From my understanding, it means that the user sets the third shrink factor to 0, which is not handled by the filter.
Concerning shrink factors, ITK says:
"*Values are clamped to a minimum value of 1. Default is 1 for all dimensions.*"
=> [shrinkFilter] shrink factors > 0 (very simple PR)

app/medInria/medRegistrationWorkspace.cpp, src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src-plugins/itkFilters/itkFiltersToolBox.cpp, src-plugins/itkFilters/itkMorphologicalFiltersToolBox.cpp, src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemonsToolBox.cpp, src-plugins/manualRegistration/manualRegistrationToolBox.cpp, src-plugins/medClut/medClutToolBox.cpp, src-plugins/reformat/reformatToolBox.cpp, src/medCore/gui/commonWidgets/medComboBox.h, src/medCore/gui/toolboxes/medCompositeDataSetImporterSelectorToolBox.cpp, src/medCore/gui/toolboxes/medDiffusionSelectorToolBox.cpp, src/medCore/gui/toolboxes/medFilteringSelectorToolBox.cpp, src/medCore/gui/toolboxes/medRegistrationSelectorToolBox.cpp, src/medCore/gui/toolboxes/medSegmentationSelectorToolBox.cpp, src/medCore/gui/toolboxes/medToolBox.h, src/medCore/parameters/medStringListParameter.cpp
Here is an annoying bug: 
you have a big toolbox, you scroll down, then you accidentally hover a QComboBox and the wheel event is caught by this comboBox, which messes up the toolbox.
Here is the solution I found on the internet: 
- You first have to prevent the comboBox from having focus on mouse wheel event
```c++
this->setFocusPolicy(Qt::StrongFocus); //the widget accepts focus by both tabbing and clicking
```
- Then you have to accept wheel events only when the widget has focus, this means that you have to subclass QComboBox to reimplement ```QComboBox::wheelEvent()```.
I have included the header of this new class in ```medToolBox.h``` since it will be mostly/only used in toolboxes.
I made the changes in the toolboxes and in medStringListParameter (i.e LUT, Preset parameters). …
=> medComboBox, QComboBox without scrolling mess

src/medCore/gui/medAbstractWorkspace.h
Just noticed this.
Destructor for medAbstractWorkspace should be virtual.
=> [medAbstractWorkspace] virtual destructor

src/medImageIO/itkDataImageWriterBase.cpp
Enables compression of data.
My results with the different writers impacted (forget about dim format).
I've done the tests on a MR image and on a mask.
Good news is we don't need to change the readers, so the previous versions of MUSIC can read the compressed data.
The compression is lossless.
=> itkDataImageWriterBase use compression on

src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medDatabaseController.cpp, src/medCore/gui/settingsWidgets/medDatabaseSettingsWidget.cpp, src/medCore/gui/settingsWidgets/medDatabaseSettingsWidget.h
Current behaviour : 
when you selected a dir, it was moving the db in this dir: cut and paste.
Now,
when you select a dir:
if this dir is empty, it creates a brand new database.
if this dir is not empty AND has a db file in it, it simply points on this db.
in other cases, the change is not applied.
I also managed the case where the db path does not exist anymore (if it were on an external hard disk that has been ejected) for reading and writing on the db.
=> Modify database directory 

src-plugins/manualRegistration/manualRegistrationToolBox.cpp, src-plugins/manualRegistration/manualRegistrationToolBox.h
Allows to use manual registration outside of a pipeline.
For this, it has two behaviours:
- in the registration workspace: inputs are in the proposed containers, output is shown in the Fuse Tab.
- in a pipeline: the toolbox has to create and manage its own containers.
You know that you are in the reg. workspace when you have a *parentToolBox*.
For now, the robustness of the toolbox in the workspace is quite poor, mainly when you switch between registration algorithms; but it does the job as long as you stay simple.
I hesitated to make this PR as it is far from perfect, but let's call it a beginning, other PRs will be done to improve this; I'd rather not complexify this one to have it merged asap.
=> Adapts Manual reg. to registration workspace

app/medInria/medDatabaseDataSource.cpp, src/medCore/gui/database/medDatabaseView.cpp, src/medCore/gui/toolboxes/medActionsToolBox.cpp, src/medCore/gui/toolboxes/medActionsToolBox.h
For now, you can only export series by series, which, if you want to export a whole patient, can be quite of a pain.
This PR brings the export function to study and patient.
Also medActionTbx (the tbx in the Browser) was not updated when selecting a study, so I added a behaviour.
=> Export of study and patient 

src/medVtkInria/vtkImageView/vtkImageView3D.cxx
The (MUSIC) [commit that adds it](https://github.com/LoicCadour/medInria-public/commit/afa5f8c87bee063ed6f7e3a5919d59c1957e17d8) aimed at improving VR when some layers were hidden. Can't find the need of this particular line.
=> Fixes crash when dropping mesh then image

src-plugins/itkFilters/itkMorphologicalFiltersToolBox.cpp
Need this to properly hide or check the buttons for mm or pixel radii in the morphological steps.
=> [itkMorphologicalFiltersToolBox] pixels button object name

src-plugins/itkFilters/itkFiltersToolBox.cpp
Need this too for the pipelines. (By factorising the pipeline code, some crashes have appeared relating to missing object names, which explains these mini-PRs).
=> [itkFiltersToolBox] object name for run button

src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp, src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h, src-plugins/itkDataImage/writers/itkMetaDataImageWriter.cpp, src-plugins/itkDataImage/writers/itkMetaDataImageWriter.h, src/medCore/views/medAbstractLayeredView.cpp
Scene saving was mostly tested with meshes.
As reported in https://github.com/Inria-Asclepios/music/issues/210, there were some issues with the volumes.
* Part of it was that the extension (.mhd, .gipl, etc) of the volume in the xml didn't match the real one. This was because, when naming a file in the xml, we didn't go through the possible writers the same way we do when writing (saving) the data.
To make it clear, i did the test with the classic I1.mhd; its name was I1.gipl in the xml.
* Correcting that, I also noticed that the a method was missing in ```itkMetaDataImageWriter```(the one handling .mhd files).
* Finally the windowing was saved but not applied when opening scenes with volumes.
Tests are more than needed to approve/disapprove this PR, so please do some (with meshes and …
=> Improving scene saving 

src/medVtkInria/vtkDataManagement/vtkMetaDataSet.cxx
Default windowing of sequences sucks, due to the removal of some code a long time ago by an emerging genius.
Proof that anyone can make mistake.
=> Fixes windowing issues with sequences

src/medCore/database/medDatabaseController.cpp
Pb is due ti the fact that the path of the db doesn't exist, i.e *.../local/INRIA_IHU-LIRYC/MUSIC/* has not been created.
The code I am removing was originally written to manage the rare case where your db path points on an external hard disk, and for some reason you start MUSIC without the external HD. It was preventing to create a new path (= creating new folders) like : /Volume/externalHD/MUSIC ... and create a new db there.
In the end it's not a big deal, since the user can easily notice that MUSIC is not pointing at the right db and since he was able at first hand to change his db path, he could do it again.
=> [URGENT] Solves db creation problem on Linux and Mac 

src/medUtilities/medUtilities.cpp
I got the duplication/overwriting bug we had a while back while importing data. The function ```generateSeriesAndSOPInstanceId``` fixed this before, but I got the bug on the output of registration. I corrected this by generating a new series DICOM ID in addition to the series ID that is already generated.
=> [medUtilities] seriesDicomId
